language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MdUo+4muos03QU3ofVY17do/6pHuLDQm+Y9nK3FUQipRxhFt/+yGlyTyffu4UlO5YDwZ/CoaRzEszeXWhWw6zgDYe9AaJYcrX5dMsHxl04fBe+tlc/L8oEyDiLAZxwVi5YTMs1D7K4JA5m1yB6A6S2Z3cIFdT8hfGP9wsNeS964Auh4Pygurr4fcaKs6oZzw3d9pYU8UwihNSOnvvjcIvFDwZTfDFe3KDwdf5xsEcyPGamUY+bwmsob58c9/sjA2Gx6gC2Zn6C+gwocObrddROlDYghszVvp/nWGXeWqDMAkCCQyIv1+Z33veNHPpH2sOIrg/iiJ7Bst0dIv2lxaXxs8fHdaRez5uqJd7qZEQPzZYsZOmnLeOSmJoRUbxBH5086fpzBmmzQb5+OsvpKAz726AXYowVurmFZZzAAuLHkFRTLETsB+7KF2ym5B0uUlzldfE7MY+7zFhR/j0G9jq5Utpn4fbNgaiivgpgmAFohOLgRxMzXzZC2a6/h0hyvhebhEWtywiL8vR3o84CO40hbMh5gOJ2n05xweYzXVIMuBSttrSkJXiP8+fM+8k7+nr1+lt9SrUxjPSX3Uk7XCj3q67lpRGjl5a1r582tc/GDaXRlue+/Fj6fUUzn2MjyRv8RjQN/kk/4g13RcnNjHVjVgmqOPkHgoTD4JryTYtiI="
